### ISSUE TITLE
Filter frequency in the butterworth filter in your readme is incorrect

### ISSUE THREAD

**Issue by moorepants** [alcantarar/dryft#22]
You need a correction factor to use butterworth and filtfilt.

See https://github.com/moorepants/DynamicistToolKit/blob/master/dtk/process.py#L465 for a correct implementation.

**Comment by alcantarar** [comment]
Thanks for pointing this out! This sent me quite far down a rabbit hole...

I cracked open Research Methods in Biomechanics (2e) and saw that Tim Derrick mentions a correction factor for a low-pass butterworth requiring more than one pass [pg 288](https://user-images.githubusercontent.com/38192529/69463278-6d38f380-0d38-11ea-86b4-66d79a78b691.jpg). But he never converts it back to Hz from rad/s. 

So, I opened up Winter's Biomechanics and Motor Control of Human Movement (4e) and on pages [68-69](https://user-images.githubusercontent.com/38192529/69474265-384e9000-0d7c-11ea-91cd-0470433431bb.png) it shows you how to calculate the coefficients yourself for a 2nd order lowpass butterworth filter with 2 passes:
```
import numpy as np

fc = 50
fs = 300
n_pass = 2
order = 2

# By hand from Winter's book (4e) pg 68-69
C = (2**(1/n_pass) - 1)**(1/(2*order))

Wc = (np.tan(np.pi*fc/fs))
Wn = Wc/C

K = np.sqrt(2)*Wn
K2 = Wn**2
a0 = K2/(1+K+K2)
a1 = 2*a0
a2 = a0
K3 = (2*a0)/K2
b1 = -2*a0 + K3
b2 = 1-2*a0 - K3

b = np.array([a0, a1, a2])  # array([0.20425381, 0.40850763, 0.20425381])
a = np.array([1, -b1, -b2])  # array([ 1.        , -0.38023186,  0.19724711])
```
But using the method described in your DynamicistToolKit, I get slightly different values:
```
import numpy as np
from scipy.signal import butter

nyquist_frequency = 0.5*fs
correction_factor = (np.sqrt(2.0) - 1.0) ** (-1.0 / (2.0 * order))
Wn2 = correction_factor * fc / nyquist_frequency
b2, a2 = butter(order, Wn2)
# b2 = array([0.21923271, 0.43846542, 0.21923271])
# a2 = array([ 1.        , -0.31189073,  0.18882157])
```
So had to [dig a little deeper](https://i.kym-cdn.com/entries/icons/facebook/000/022/524/tumblr_o16n2kBlpX1ta3qyvo1_1280.jpg) and found an [article](https://www.codeproject.com/Articles/1267916/Multi-pass-Filter-Cutoff-Correction) about this very issue! 

It suggested this method, which relies on `Wn` from Winter's book, reproduces the coefficients, and (supposedly) scales with other filter orders:
```
import numpy as np
from scipy.signal import butter

fc_corrected_hz = np.arctan(Wn)*fs/np.pi  
b3,a3 = butter(order, fc_corrected_hz/(fs/2))
# b3 = array([0.20425381, 0.40850763, 0.20425381])
# a3 = array([ 1.        , -0.38023186,  0.19724711])
```

What do you think?

**Comment by moorepants** [comment]
Not sure off hand. I "dug a little deeper" some years ago on it too and thought I implemented it correctly, but it is possible I didn't. I'd have to spend some time to see what the differences are and why. Probably won't have time till school lets out.
