### ISSUE TITLE
Recommended installation adds unnecessary conda dependency

### ISSUE THREAD

**Issue by agricolab** [alcantarar/dryft#29]
I appreciate that an environment.yaml was supported, but am uncertain why the author suggests a conda environment as recommended installation. Are there any dependencies that require conda? Otherwise, conda would become a hidden dependency, yet would actually not be required at all. 

I tried, and all requirements install fine from pip, and the environment can be set-up with virtualenv, too. I would argue, it should be left to the user how they want to set up their environment, if at all.

An option is to split the instructions into a "classical" installation and one for "environments", with this example using conda.

**Comment by alcantarar** [comment]
@agricolab does the `pip`/`requirements.txt` method described in the README.md implemented with commit https://github.com/alcantarar/dryft/commit/5d6ee147bb180c958ab866583946b2108e6b0433 work for you?

**Comment by agricolab** [comment]
requirements.txt seems fine. For the instructions using virtualenv, the final  "python setup.py install" or "pip install ." seems to be missing .
