### ISSUE TITLE
Discuss performance claims

### ISSUE THREAD

**Issue by agricolab** [alcantarar/dryft#34]
Author appears to suggest his approach is superior to other methods, as

> dryft does not assume a constant drift for a given step, instead spline interpolating between aerial phases. The dryft package differs from currently available signal correction methods, which can only account for linear drift or a constant offset.

While i agree with the author that spline interpolation is theoretically better, author might want to add some numbers to this claim.

**Comment by alcantarar** [comment]
Hi @agricolab, thank you for all the great feedback and the issues you opened up. 

A numerical comparison between `dryft` and the method described in [Paolini et al](https://www.ncbi.nlm.nih.gov/pubmed/16759895) could help illustrate differences in performance, but their methodology is not thoroughly explained nor software provided. They summarize their drift correction method in their manuscript,

>In order to cope with this problem we developed a software routine compensating for the drift
by removing throughout the experimental trial the average of the recorded force signals during each swing phase from the force signals recorded during the following stance phase

but the success of this method is highly dependent upon the method of identifying aerial phases, the magnitude of the drift, and the slope of the drift in the ground reaction force signal, which will vary greatly. These issues prevent any accurate performance comparisons. For this reason, I try to focus on differences in methodology in the README.

Per your suggestion, I have revised this section of the README to discuss this comparison further in commit 123eab5.

**Comment by agricolab** [comment]
I see. I took a look at Paolini et al. and their description is very meager. Your work is certainly  improving on that.
